### ISSUE TITLE
Running the memoryinspector in WSL

### ISSUE THREAD

**Issue by jlonnberg** [eclipse-cdt-cloud/vscode-memory-inspector#150] opened 2024-10-31 13:12 UTC
**Description**
The extensions fails to activate properly when running in WSL

**How to reproduce:**
Launch a simple gcc project in WSL and try to use the extension

**Expected behavior**
The extension is activated properly in WSL

**Environment**
 - _OS_: WSL, Ubuntu 22.04 on windows 11
 - _Browser_:
 - _Theia or VS Code Version_:

**Additional information**

**Comment by thegecko** [comment] 2024-11-06 10:09
Thanks for raising this issue. The behaviour seen here is due to a culmination of a few things:

- VS Code has multiple runtime environments or extension hosts and in some setups, the workspace host is separated from the UI host. This is the case with VS Code remote, WSL and codespaces
- Debuggers have to run in one of these hosts and each host isn't aware of debug sessions running in other hosts
- This extension has to run in the same host as the debugger in order to interact with it

The host an extension runs in is outlined using the `extensionKind` `package.json` entry and we currently have this set to `ui` for the following reasons:

- It works in the normal desktop version of VS Code (as would `workspace` TBF)
- Arm have a unique use case where we run a debugger in the UI extension host to enable [browser-based debugging](https://marketplace.visualstudio.com/items?itemName=Arm.embedded-debug) of physical hardware from an online IDE (e.g. [Keil Studio Cloud](https://www.keil.arm.com/))

However this setup means the memory inspector extension doesn't see any debuggers running in remote hosts.

In order to resolve this issue, we need to decide where we want this extension to run. The options boil down to:

1. Keep the existing setup. Desktop and browser debug will continue to work, but remote debug scenarios wont be supported.
2. Change this to run in the workspace. Desktop and remote scenarios will work, but browser debugging will not.

I will separately raise a question with the VS Code team to get their input.

As this is an OSS project and the UI use case may be unique to Arm, I suggest we go with option `2` and change the default behaviour to support remote workspaces. Arm then need to investigate a workaround for our browser scenario.

Feedback welcome @jreineckearm

**Comment by jlonnberg** [comment] 2024-11-06 10:13
@thegecko There's also the option to list the extension as UI preferred and workspace as secondary option. This did the trick for us when trying to figure out what the problem was

**Comment by thegecko** [comment] 2024-11-06 10:18
> @thegecko There's also the option to list the extension as UI preferred and workspace as secondary option. This did the trick for us when trying to figure out what the problem was

Hmm, my tests in that scenario didn't work. But if it did, it would still break the browser scenario :(
Would you mind confirming if this fixes your setup:

```json
...
"extensionKind": [
  "ui",
  "workspace"
]
...
```

In order for this to continue to work in a serverless environment (vscode.dev) it would still need `UI` in the list somewhere.

If you can confirm this setup works for you

**Comment by jlonnberg** [comment] 2024-11-06 10:24
@thegecko Yes, that solved the problem for us at least

**Comment by colin-grant-work** [comment] 2024-11-06 19:07
> But if it did, it would still break the browser scenario :(

Our experience is also that you basically have to commit to one extension host or the other when working remotely. The Memory Inspector will only run in one extension host, and that needs to be the one that runs the debugger. If you had different debuggers running in the different hosts, only one would work with the Memory Inspector. For our use cases we prefer the workspace extension host, so we've just modified the `package.json` accordingly, but it's an unfortunate limitation.

**Comment by thegecko** [comment] 2024-11-07 08:51
Changed in #151

**Comment by thegecko** [comment] 2024-11-07 15:23
>Hmm, my tests in that scenario didn't work...
...Yes, that solved the problem for us at least

Forgot to mention, I confirmed the PR linked above does indeed fix WSL support in my test setup

**Closed** 2024-12-23 17:56 UTC
Labels: bug

**Comment by mvimercati** [comment] 2025-03-03 10:55
Hi,
my configuration is the following
VScode on windows -> WSL with docker -> toolchain in a container

I'm still not able to run the memory inspector into the container. I didn't understand if those patches address also this scenario.
I tried with CPPDBG and also with CDT debugger

(Added gdbtarget / cppdgb in debugTypes for the Memory Inspector).

Actually the extension seems not installed in the container...

**Comment by colin-grant-work** [comment] 2025-03-03 15:40
The Memory Inspector should now have access to sessions running in the 'backend' extension host for your setup. For you, that should be the container, but all of the tools that you want to work together in the extension host running in that container would need to be installed there. Let us know if you find that the Memory Inspector still doesn't work for the sessions you're running even when everything is definitely running together in the container.

**Comment by mvimercati** [comment] 2025-03-03 15:52
How can I check that the Memory Inspector is effectively installed in the container? From the extension's list in vscode it seems not (Differently from the CDT GDB adapter, that is marked as Extension is enabled on 'Dev Container: ............'), but then I can find the Memory Inspector settings in the Remote container settings page. I'm a bit confused

**Comment by jreineckearm** [comment] 2025-03-03 16:40
I think we haven't released the change #151 yet. Last release to VS Code Marketplace / OpenVSX was in late March 2024.
@mvimercati , did you try this with a local build of the extension? Or the latest release from the marketplace/OpenVSX?

**Comment by mvimercati** [comment] 2025-03-03 16:46
> I think we haven't released the change [#151](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/151) yet. Last release to VS Code Marketplace / OpenVSX was in late March 2024.
> [@mvimercati](https://github.com/mvimercati) , did you try this with a local build of the extension? Or the latest release from the marketplace/OpenVSX?

It's the one from the marketplace. Maybe this could explain...

**Comment by jreineckearm** [comment] 2025-03-03 18:33
Note that I started a Draft to prepare a release here: https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/pull/158
May need some further updates, hope to continue in the coming days.

**Comment by jreineckearm** [comment] 2025-03-26 10:08
@mvimercati , we just released Memory Inspector v1.2.0 which should contain the above fix. Please let us know if it works for you. If not, then please create a new [issue ](https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/issues/new/choose).

**Comment by mvimercati** [comment] 2025-03-26 11:22
@jreineckearm great! I confirm that now it's wokring (Container running in WSL's docker).
Do you know if is it possible to associate the Memory Inspector to the "View Binary Data" icon next to each variable in the variables' list?

**Comment by jreineckearm** [comment] 2025-03-26 12:40
Thanks for confirming, @mvimercati !

**Comment by mvimercati** [comment] 2025-03-26 16:28
> > Do you know if is it possible to associate the Memory Inspector to the "View Binary Data" icon
> 
> [microsoft/vscode#155597](https://github.com/microsoft/vscode/issues/155597)

ufff... read that you have done lot of work on this topic, also a pr that was not merged :|
